
name: Arduino-lint

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Arduino-CI/action@stable-1.x
        with:
          library-manager: update
          compliance: strict
